<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="src/Shared.fs" />
        <Compile Include="src/Pages/NotFound.fs" />
        <Compile Include="src/Pages/Layout.fs" />
        <Compile Include="src/Pages/Page.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include=".elmish-land/Base/ElmishLand.LmuRaces.Base.fsproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Feliz.Lucide" />
      <PackageReference Include="Feliz.RadixUI.Interface" />
      <PackageReference Include="Feliz.Shadcn" />
      <PackageReference Include="Feliz.Shadcn.Interop" />
      <PackageReference Include="Thoth.Fetch" />
      <PackageReference Include="Thoth.Json" />
    </ItemGroup>
</Project>
