//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by elmish-land.
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

module ElmishLand.LmuRaces.App

open Elmish
open Elmish.HMR
open Feliz
open Feliz.Router
open Feliz
open ElmishLand
open LmuRaces
open LmuRaces.Shared

[<RequireQualifiedAccess>]
type LayoutName =
    | Main
    | None

[<RequireQualifiedAccess>]
type Layout =
    | Main of LmuRaces.Pages.Layout.Props * LmuRaces.Pages.Layout.Model
    | None

[<RequireQualifiedAccess>]
type LayoutMsg =
    | MainMsg of LmuRaces.Pages.Layout.Msg
    | NoOp

[<RequireQualifiedAccess>]
type PageMsg =
    | HomeMsg of LmuRaces.Pages.Page.Msg

type Msg =
    | SharedMsg of SharedMsg
    | RouteChanged of Route
    | PageMsg of PageMsg
    | LayoutMsg of LayoutMsg

type MappedPage<'pageMsg, 'pageModel, 'layoutMsg, 'layoutProps> =
    {
        Init: unit -> 'pageModel * Command<Msg, SharedMsg, Msg>
        Update: 'pageMsg -> 'pageModel -> 'pageModel * Command<Msg, SharedMsg, Msg>
        View: 'pageModel -> ('pageMsg -> unit) -> ReactElement
        Subscriptions: 'pageModel -> (string list * (('pageMsg -> unit) -> System.IDisposable)) list
        LayoutProps: 'layoutProps
        LayoutMsgToPageMsg: 'layoutMsg -> 'pageMsg
        LayoutMsgToMsg: 'layoutMsg -> Msg
    }

[<RequireQualifiedAccess>]
type PageModel =
    | Home of LmuRaces.Pages.Page.Model
    | NotFound

[<RequireQualifiedAccess>]
type Page =
    | Home of MappedPage<LmuRaces.Pages.Page.Msg, LmuRaces.Pages.Page.Model, LmuRaces.Pages.Layout.Msg, LmuRaces.Pages.Layout.Props>
    | NotFound

type Model = {
    Shared: SharedModel
    CurrentRoute: Route
    CurrentPage: Page
    CurrentPageModel: PageModel
    CurrentLayout: Layout
    CurrentLayoutName: LayoutName
    PageModelByLayout: Map<LayoutName, Page>
}

let rec commandToCmd fromSharedMsg fromLayoutMsg command =
    match command with
    | Command.None -> Cmd.none
    | Command.Batch cmds -> Cmd.batch (List.map (commandToCmd fromSharedMsg fromLayoutMsg) cmds)
    | Command.Cmd cmd -> cmd
    | Command.SharedMsg msg -> Cmd.ofMsg (fromSharedMsg msg)
    | Command.LayoutMsg msg -> Cmd.ofMsg (fromLayoutMsg msg)

let getMainLayout currentLayout currentRoute sharedModel layoutProps =
    let layout = LmuRaces.Pages.Layout.layout layoutProps currentRoute sharedModel
    match currentLayout with
    | Layout.Main (_, m) -> layout.RouteChanged m
    | _ -> layout.Init ()

let mapPage (f: 'pageMsg -> Msg) (mapLayout: 'layoutMsg -> Msg) (p: Page<SharedMsg, 'pageModel, 'pageMsg, 'layoutMsg, 'layoutProps>)
    : MappedPage<'pageMsg, 'pageModel, 'layoutMsg, 'layoutProps> =
    let init = p.Init >> fun (m, c) -> m, Command.map f mapLayout c
    let update =
        p.Update >>
        fun f' -> f'
                >> fun (m: 'pageModel, c: Command<'pageMsg, SharedMsg, 'layoutMsg>) ->
                    (m, Command.map f mapLayout c)
    let layoutMsgToPageMsg layoutMsg =
        p.LayoutMsgToPageMsg layoutMsg |> f

    {
        Init = init
        Update = update
        View = p.View
        Subscriptions = p.Subscriptions
        LayoutProps = p.LayoutProps
        LayoutMsgToPageMsg = p.LayoutMsgToPageMsg
        LayoutMsgToMsg = layoutMsgToPageMsg
    }

let layoutMsgToPageMsg page f layoutMsg = page.LayoutMsgToPageMsg layoutMsg |> f

let initHomePage model route sharedCmd =
    let mappedPage = (LmuRaces.Pages.Page.page model.Shared route |> mapPage (PageMsg.HomeMsg >> PageMsg) (LayoutMsg.MainMsg >> LayoutMsg))
    let pageModel, pageCmd = mappedPage.Init ()
    let layoutModel, layoutCmd = (getMainLayout model.CurrentLayout (Route.Home route)) model.Shared mappedPage.LayoutProps
    let layout = Layout.Main (mappedPage.LayoutProps, layoutModel)
    {
        model with
            CurrentRoute = Route.Home route
            CurrentPage = Page.Home mappedPage
            CurrentPageModel = PageModel.Home pageModel
            CurrentLayout = layout
            CurrentLayoutName = LayoutName.Main
            PageModelByLayout = Map.change LayoutName.Main (fun _ -> Some (Page.Home mappedPage)) model.PageModelByLayout
    },
    Command.batch [
        sharedCmd
        pageCmd
        Command.map mappedPage.LayoutMsgToMsg mappedPage.LayoutMsgToMsg layoutCmd
        Command.map (LayoutMsg.MainMsg >> LayoutMsg) (LayoutMsg.MainMsg >> LayoutMsg) layoutCmd
    ] |> commandToCmd SharedMsg id

let init () =
    let initialUrl = Route.parse (Router.currentUrl ())
    let sharedModel, sharedCmd = Shared.init ()

    let defaultModel = {
        Shared = sharedModel
        CurrentRoute = initialUrl
        CurrentPage = Page.NotFound
        CurrentPageModel = PageModel.NotFound
        CurrentLayout = Layout.None
        CurrentLayoutName = LayoutName.None
        PageModelByLayout = Map.empty
    }

    match initialUrl with
    | Route.Home route ->
        initHomePage defaultModel route sharedCmd
    | Route.NotFound ->
        {
            defaultModel with
                CurrentPage = Page.NotFound
        },
        Cmd.none

let update (msg: Msg) (model: Model) =
    let updateLayout (model: Model) (layout: Layout<_,_,_>) props model' mapLayout layoutMsg msg pageCmd =
        let model'', cmd = layout.Update layoutMsg model'

        {
            model with
                CurrentLayout = mapLayout (props, model'')
        },
        Command.batch [
            Command.map msg msg cmd
            pageCmd
        ]
        |> commandToCmd SharedMsg id

    match msg with
    | SharedMsg msg' ->
        let model'', cmd = Shared.update msg' model.Shared
        { model with Shared = model'' }, commandToCmd SharedMsg Unchecked.defaultof<_> cmd
    | RouteChanged nextRoute ->
        if model.CurrentRoute = nextRoute then
            model, Cmd.none
        else
            match nextRoute with
            | Route.Home route ->
                initHomePage model route Command.none
            | Route.NotFound ->
                {
                    model with
                        CurrentPage = Page.NotFound
                        CurrentRoute = Route.NotFound
                        CurrentLayout = Layout.None
                        CurrentLayoutName = LayoutName.None
                },
                Cmd.none
    | PageMsg pageMsg ->
        match model.CurrentPage, pageMsg, model.CurrentPageModel with
        | Page.Home mappedPage, PageMsg.HomeMsg pageMsg', PageModel.Home pageModel ->
            let pageModel, pageCmd = mappedPage.Update pageMsg' pageModel
            {
                model with
                    CurrentPageModel = PageModel.Home pageModel
            },
            commandToCmd SharedMsg id pageCmd
        | currentPage, pageMsg, currentPageModel ->
            printfn $"Unhandled CurrentPage, PageMsg, CurrentPageModel, CurrentRoute. Got\nCurrentPage:\n%A{currentPage}\nPageMsg:\n%A{pageMsg}\nCurrentPageModel:\n%A{currentPageModel}"
            model, Cmd.none
    | LayoutMsg layoutMsg ->
        let updatePage layoutMsg =
            model.PageModelByLayout
            |> Map.tryFind model.CurrentLayoutName
            |> function
                | Some p ->
                    match p, model.CurrentPageModel, layoutMsg with
                    | Page.Home mappedPage, PageModel.Home m, LayoutMsg.MainMsg layoutMsg' ->
                        let pageMsg = mappedPage.LayoutMsgToPageMsg layoutMsg'
                        let m, cmd = mappedPage.Update pageMsg m
                        { model with
                            CurrentPageModel = PageModel.Home m
                        }
                        , cmd
                    | _ -> model, Command.none
                | _ -> model, Command.none

        match layoutMsg, model.CurrentLayout with
        | LayoutMsg.MainMsg layoutMsg', Layout.Main (props, model') ->
            let model, pageCmd = updatePage (LayoutMsg.MainMsg layoutMsg')
            let layout = (LmuRaces.Pages.Layout.layout props model.CurrentRoute model.Shared)
            updateLayout model layout props model' Layout.Main layoutMsg' (LayoutMsg.MainMsg >> LayoutMsg) pageCmd
        | layoutMsg', layout ->
            printfn $"Unhandled LayoutMsg and CurrentLayout. Got\nLayoutMsg:\n%A{layoutMsg'}\nCurrentLayout:\n%A{layout}"
            model, Cmd.none

let inline (|Renderable|) (o: 'x when 'x: (member Render: unit -> ReactElement)) = o

let view (model: Model) (dispatch: Msg -> unit) =
    let currentPageView =
        match model.CurrentPageModel, model.CurrentRoute with
        | PageModel.Home m, Route.Home route ->
            (LmuRaces.Pages.Page.page model.Shared route).View m (PageMsg.HomeMsg >> PageMsg >> dispatch)
        | _ -> LmuRaces.Pages.NotFound.view ()

    let currentView =
        match model.CurrentLayout with
        | Layout.Main (props, m) ->
            (LmuRaces.Pages.Layout.layout props model.CurrentRoute model.Shared).View m currentPageView (LayoutMsg.MainMsg >> LayoutMsg >> dispatch)
        | Layout.None -> currentPageView

    let currentReactElement =
        currentView

    React.router [
        router.onUrlChanged (Route.parse >> RouteChanged >> dispatch)
        router.children [ currentReactElement ]
    ]

let subscribe model =
    Sub.batch [
        Sub.map "Shared" SharedMsg (Shared.subscriptions model.Shared)
        match model.CurrentLayout with
        | Layout.Main (props, m) -> Sub.map "LayoutMain" (LayoutMsg.MainMsg >> LayoutMsg) ((LmuRaces.Pages.Layout.layout props model.CurrentRoute model.Shared).Subscriptions m)
        | _ -> Sub.none
        match model.CurrentRoute, model.CurrentPageModel with
        | Route.Home route, PageModel.Home pageModel ->
            Sub.map "PageHome" (PageMsg.HomeMsg >> PageMsg) ((LmuRaces.Pages.Page.page model.Shared route).Subscriptions pageModel)
        | _ -> Sub.none
    ]

Program.mkProgram init update view
|> Program.withErrorHandler (fun (msg, ex) -> printfn "Program error handler:\r\n%s\r\n%O" msg ex)
|> Program.withReactBatched "app"
|> Program.withSubscription subscribe
|> Program.run
